services:
  Plastimatch:
    build:
      context: ../
      dockerfile: docker_src/Dockerfile
      ssh:
        - default
    image: plastimatch:latest
    container_name: Plastimatch
    user: "${UID}:${GID}"
    working_dir: /app
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      - HOST_HOME=${HOST_HOME}
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../plastimatch-api.py:/app/Software/SimpleElastix-brachyutils/plastimatch-api.py
      # - ../run_api.sh:/app/Software/SimpleElastix-brachyutils/run_api.sh
      - ${HOST_HOME}:/home/ubuntu/YourLocalHome
      - ../temp_data:/app/Software/plastimatch-brachyutils/temp_data
    # entrypoint: ["/bin/bash"]
    # command: ["/app/Software/plastimatch-brachyutils/run_api.sh"]